// Generated by `deno task gen:messages` from `../en.ts`. Do not edit.
/** The en catalog as ICU AST. */
export const IAM_UI_MESSAGES_EN_COMPILED: Readonly<
  Record<string, { type: number; value?: string; [key: string]: unknown }[]>
> = {
  'common/back-to-sign-in': [
    {
      'type': 0,
      'value': 'Back to sign in',
    },
  ],
  'common/invalid-or-expired-code': [
    {
      'type': 0,
      'value': 'Invalid or expired code.',
    },
  ],
  'common/try-again': [
    {
      'type': 0,
      'value': 'Try again',
    },
  ],
  'common/verify': [
    {
      'type': 0,
      'value': 'Verify',
    },
  ],
  'consent/heading': [
    {
      'type': 0,
      'value': 'Cookie consent',
    },
  ],
  'login/email-label': [
    {
      'type': 0,
      'value': 'Email',
    },
  ],
  'login/email-placeholder': [
    {
      'type': 0,
      'value': 'you@example.com',
    },
  ],
  'login/heading': [
    {
      'type': 0,
      'value': 'Sign in or create an account',
    },
  ],
  'login/invalid-credentials': [
    {
      'type': 0,
      'value': 'Invalid email or password.',
    },
  ],
  'login/legal-and': [
    {
      'type': 0,
      'value': 'and',
    },
  ],
  'login/legal-prefix': [
    {
      'type': 0,
      'value': 'By continuing, you agree to our',
    },
  ],
  'login/no-account': [
    {
      'type': 0,
      'value': 'No account exists for that email.',
    },
  ],
  'login/oauth-continue': [
    {
      'type': 0,
      'value': 'Continue with ',
    },
    {
      'type': 1,
      'value': 'provider',
    },
  ],
  'login/oauth/callback-continue': [
    {
      'type': 0,
      'value': 'Continue',
    },
  ],
  'login/oauth/callback-heading': [
    {
      'type': 0,
      'value': 'Signed in',
    },
  ],
  'login/oauth/error-body': [
    {
      'type': 0,
      'value': 'Something went wrong finishing sign-in. You can try again from the sign-in page.',
    },
  ],
  'login/oauth/error-heading': [
    {
      'type': 0,
      'value': "Sign-in didn't complete",
    },
  ],
  'login/or-email': [
    {
      'type': 0,
      'value': 'or continue with email',
    },
  ],
  'login/otp/code-label': [
    {
      'type': 0,
      'value': 'Verification code',
    },
  ],
  'login/otp/heading': [
    {
      'type': 0,
      'value': 'Enter your verification code',
    },
  ],
  'login/otp/notifier-email': [
    {
      'type': 0,
      'value': 'Email',
    },
  ],
  'login/otp/notifier-sms': [
    {
      'type': 0,
      'value': 'SMS',
    },
  ],
  'login/otp/notifier-whatsapp': [
    {
      'type': 0,
      'value': 'WhatsApp',
    },
  ],
  'login/otp/resend': [
    {
      'type': 0,
      'value': "Didn't get it? Resend code",
    },
  ],
  'login/otp/resend-cooldown': [
    {
      'type': 0,
      'value': 'We already sent you a code. Please wait a moment before requesting another.',
    },
  ],
  'login/otp/resend-notifier-label': [
    {
      'type': 0,
      'value': 'Send by',
    },
  ],
  'login/otp/sent-to': [
    {
      'type': 0,
      'value': 'A verification code was sent for ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'login/password-hide': [
    {
      'type': 0,
      'value': 'Hide password',
    },
  ],
  'login/password-label': [
    {
      'type': 0,
      'value': 'Password',
    },
  ],
  'login/password-show': [
    {
      'type': 0,
      'value': 'Show password',
    },
  ],
  'login/password-step/forgot-password': [
    {
      'type': 0,
      'value': 'Forgot your password?',
    },
  ],
  'login/password-step/heading': [
    {
      'type': 0,
      'value': 'Enter your password',
    },
  ],
  'login/password-step/invalid-password': [
    {
      'type': 0,
      'value': 'Incorrect password.',
    },
  ],
  'login/password-step/rate-limited': [
    {
      'type': 0,
      'value': 'Too many attempts. Wait a minute before trying again.',
    },
  ],
  'login/password-step/rate-limited/body': [
    {
      'type': 0,
      'value': 'You can try again in:',
    },
  ],
  'login/password-step/rate-limited/heading': [
    {
      'type': 0,
      'value': "For your security, we've paused sign-in attempts for a moment.",
    },
  ],
  'login/password-step/signing-in-as': [
    {
      'type': 0,
      'value': 'Signing in as',
    },
  ],
  'login/password-step/use-another-email': [
    {
      'type': 0,
      'value': 'Use another email',
    },
  ],
  'login/privacy-link': [
    {
      'type': 0,
      'value': 'Privacy Notice',
    },
  ],
  'login/rate-limited': [
    {
      'type': 0,
      'value': 'Too many attempts — please wait a minute and try again.',
    },
  ],
  'login/rate-limited/body': [
    {
      'type': 0,
      'value': 'You can try again in:',
    },
  ],
  'login/rate-limited/heading': [
    {
      'type': 0,
      'value': "For your security, we've paused sign-in attempts for a moment.",
    },
  ],
  'login/reactivate/body': [
    {
      'type': 0,
      'value':
        "If you continue, your account will be reactivated automatically and you'll be able to use it normally again.",
    },
  ],
  'login/reactivate/cancel': [
    {
      'type': 0,
      'value': 'Cancel',
    },
  ],
  'login/reactivate/confirm': [
    {
      'type': 0,
      'value': 'Yes, reactivate my account',
    },
  ],
  'login/reactivate/expired': [
    {
      'type': 0,
      'value':
        'This reactivation link is no longer valid or has expired. Sign in again to get a new one.',
    },
  ],
  'login/reactivate/heading': [
    {
      'type': 0,
      'value': 'Your account is deactivated',
    },
  ],
  'login/session-expired': [
    {
      'type': 0,
      'value': 'Your session expired. Sign in again to continue.',
    },
  ],
  'login/submit': [
    {
      'type': 0,
      'value': 'Sign in',
    },
  ],
  'login/subtext': [
    {
      'type': 0,
      'value': 'Enter your email, or continue with a provider below.',
    },
  ],
  'login/subtext-no-oauth': [
    {
      'type': 0,
      'value': 'Enter your email to continue.',
    },
  ],
  'login/terms-link': [
    {
      'type': 0,
      'value': 'Terms and Conditions',
    },
  ],
  'login/totp/code-label': [
    {
      'type': 0,
      'value': 'Authenticator code',
    },
  ],
  'login/totp/heading': [
    {
      'type': 0,
      'value': 'Enter your authenticator code',
    },
  ],
  'login/totp/invalid-code': [
    {
      'type': 0,
      'value': 'Invalid authenticator code.',
    },
  ],
  'login/totp/rate-limited': [
    {
      'type': 0,
      'value': 'Too many attempts. Wait a minute before trying again.',
    },
  ],
  'login/totp/rate-limited/body': [
    {
      'type': 0,
      'value': 'You can try again in:',
    },
  ],
  'login/totp/rate-limited/heading': [
    {
      'type': 0,
      'value': "For your security, we've paused sign-in attempts for a moment.",
    },
  ],
  'login/totp/signing-in-as': [
    {
      'type': 0,
      'value': 'Signing in as ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'login/totp/unexpected-error': [
    {
      'type': 0,
      'value': 'Something went wrong verifying your code. Please try again in a moment.',
    },
  ],
  'login/unexpected-error': [
    {
      'type': 0,
      'value': 'Something went wrong signing you in. Please try again.',
    },
  ],
  'logout/cancel-link': [
    {
      'type': 0,
      'value': 'Never mind',
    },
  ],
  'logout/confirm-description': [
    {
      'type': 0,
      'value': "You'll need to sign in again on this device.",
    },
  ],
  'logout/heading': [
    {
      'type': 0,
      'value': 'Sign out',
    },
  ],
  'logout/submit': [
    {
      'type': 0,
      'value': 'Sign out',
    },
  ],
  'password/recovery/callback-heading': [
    {
      'type': 0,
      'value': 'Reset your password',
    },
  ],
  'password/recovery/callback-subtext': [
    {
      'type': 0,
      'value': 'We sent a recovery code to ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'password/recovery/code-label': [
    {
      'type': 0,
      'value': 'Recovery code',
    },
  ],
  'password/recovery/confirm-label': [
    {
      'type': 0,
      'value': 'Confirm password',
    },
  ],
  'password/recovery/have-code-link': [
    {
      'type': 0,
      'value': 'I have my code',
    },
  ],
  'password/recovery/mismatch': [
    {
      'type': 0,
      'value': "The passwords don't match.",
    },
  ],
  'password/recovery/password-hide': [
    {
      'type': 0,
      'value': 'Hide password',
    },
  ],
  'password/recovery/password-label': [
    {
      'type': 0,
      'value': 'New password',
    },
  ],
  'password/recovery/password-show': [
    {
      'type': 0,
      'value': 'Show password',
    },
  ],
  'password/recovery/request-body': [
    {
      'type': 0,
      'value': 'If an account exists for ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': ', a recovery code has been sent.',
    },
  ],
  'password/recovery/request-heading': [
    {
      'type': 0,
      'value': 'Check your email',
    },
  ],
  'password/recovery/submit': [
    {
      'type': 0,
      'value': 'Reset password',
    },
  ],
  'password/recovery/weak-password': [
    {
      'type': 0,
      'value': "This password doesn't meet the password requirements.",
    },
  ],
  'phone/confirm/code-label': [
    {
      'type': 0,
      'value': 'Verification code',
    },
  ],
  'phone/confirm/heading': [
    {
      'type': 0,
      'value': 'Enter the code we sent you',
    },
  ],
  'phone/confirm/sent-to': [
    {
      'type': 0,
      'value': 'We sent a code to ',
    },
    {
      'type': 1,
      'value': 'phone',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'phone/enroll/body': [
    {
      'type': 0,
      'value': "We'll text you a one-time code to confirm you own this number.",
    },
  ],
  'phone/enroll/heading': [
    {
      'type': 0,
      'value': 'Verify your phone number',
    },
  ],
  'phone/enroll/phone-label': [
    {
      'type': 0,
      'value': 'Phone number',
    },
  ],
  'phone/enroll/phone-placeholder': [
    {
      'type': 0,
      'value': '+1 555 123 4567',
    },
  ],
  'phone/enroll/submit': [
    {
      'type': 0,
      'value': 'Send code',
    },
  ],
  'totp/confirm/heading': [
    {
      'type': 0,
      'value': 'Confirm authenticator app',
    },
  ],
  'totp/enroll/code-label': [
    {
      'type': 0,
      'value': 'Authenticator code',
    },
  ],
  'totp/enroll/heading': [
    {
      'type': 0,
      'value': 'Set up an authenticator app',
    },
  ],
  'totp/enroll/invalid-code': [
    {
      'type': 0,
      'value': 'Invalid authenticator code — scan the new code below.',
    },
  ],
  'totp/enroll/scan-aria-label': [
    {
      'type': 0,
      'value': 'Scan this QR code with your authenticator app',
    },
  ],
  'totp/enroll/scan-instructions': [
    {
      'type': 0,
      'value': 'Scan this in your authenticator app, or enter the key manually:',
    },
  ],
  'totp/enroll/submit': [
    {
      'type': 0,
      'value': 'Confirm',
    },
  ],
}
