// Generated by `deno task gen:messages` from `../es.ts`. Do not edit.
/** The es catalog as ICU AST. */
export const IAM_UI_MESSAGES_ES_COMPILED: Readonly<
  Record<string, { type: number; value?: string; [key: string]: unknown }[]>
> = {
  'common/back-to-sign-in': [
    {
      'type': 0,
      'value': 'Volver a ingresar',
    },
  ],
  'common/invalid-or-expired-code': [
    {
      'type': 0,
      'value': 'Código inválido o vencido.',
    },
  ],
  'common/try-again': [
    {
      'type': 0,
      'value': 'Intentar de nuevo',
    },
  ],
  'common/verify': [
    {
      'type': 0,
      'value': 'Verificar',
    },
  ],
  'consent/heading': [
    {
      'type': 0,
      'value': 'Consentimiento de cookies',
    },
  ],
  'cookie-consent-modal/accept': [
    {
      'type': 0,
      'value': 'Aceptar',
    },
  ],
  'cookie-consent-modal/body': [
    {
      'type': 0,
      'value':
        'Este servicio necesita guardar una cookie en tu navegador — la cookie de sesión — para mantenerte conectado entre páginas. Solo existe esta cookie en este proyecto; no se rastrea nada más.',
    },
  ],
  'cookie-consent-modal/decline': [
    {
      'type': 0,
      'value': 'Rechazar',
    },
  ],
  'cookie-consent-modal/error': [
    {
      'type': 0,
      'value': 'Algo falló al registrar tu elección. Intenta de nuevo.',
    },
  ],
  'cookie-consent-modal/heading': [
    {
      'type': 0,
      'value': 'Cookie de sesión',
    },
  ],
  'login/email-label': [
    {
      'type': 0,
      'value': 'Correo electrónico',
    },
  ],
  'login/email-placeholder': [
    {
      'type': 0,
      'value': 'tucorreo@ejemplo.com',
    },
  ],
  'login/heading': [
    {
      'type': 0,
      'value': 'Inicia sesión o crea una cuenta',
    },
  ],
  'login/invalid-credentials': [
    {
      'type': 0,
      'value': 'Correo o contraseña incorrectos.',
    },
  ],
  'login/legal-and': [
    {
      'type': 0,
      'value': 'y',
    },
  ],
  'login/legal-prefix': [
    {
      'type': 0,
      'value': 'Al continuar, aceptas nuestros',
    },
  ],
  'login/no-account': [
    {
      'type': 0,
      'value': 'No existe una cuenta para ese correo.',
    },
  ],
  'login/oauth-continue': [
    {
      'type': 0,
      'value': 'Continuar con ',
    },
    {
      'type': 1,
      'value': 'provider',
    },
  ],
  'login/oauth/callback-continue': [
    {
      'type': 0,
      'value': 'Continuar',
    },
  ],
  'login/oauth/callback-heading': [
    {
      'type': 0,
      'value': 'Sesión iniciada',
    },
  ],
  'login/oauth/error-body': [
    {
      'type': 0,
      'value':
        'Algo falló al completar el inicio de sesión. Puedes intentarlo de nuevo desde la página de acceso.',
    },
  ],
  'login/oauth/error-heading': [
    {
      'type': 0,
      'value': 'No se completó el inicio de sesión',
    },
  ],
  'login/or-email': [
    {
      'type': 0,
      'value': 'o continúa con tu correo',
    },
  ],
  'login/otp/code-label': [
    {
      'type': 0,
      'value': 'Código de verificación',
    },
  ],
  'login/otp/heading': [
    {
      'type': 0,
      'value': 'Ingresa tu código de verificación',
    },
  ],
  'login/otp/notifier-email': [
    {
      'type': 0,
      'value': 'Correo',
    },
  ],
  'login/otp/notifier-sms': [
    {
      'type': 0,
      'value': 'SMS',
    },
  ],
  'login/otp/notifier-whatsapp': [
    {
      'type': 0,
      'value': 'WhatsApp',
    },
  ],
  'login/otp/resend': [
    {
      'type': 0,
      'value': '¿No te llegó? Reenviar código',
    },
  ],
  'login/otp/resend-cooldown': [
    {
      'type': 0,
      'value': 'Ya te enviamos un código. Espera un momento antes de pedir otro.',
    },
  ],
  'login/otp/resend-notifier-label': [
    {
      'type': 0,
      'value': 'Enviar por',
    },
  ],
  'login/otp/sent-to': [
    {
      'type': 0,
      'value': 'Enviamos un código de verificación a ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'login/password-hide': [
    {
      'type': 0,
      'value': 'Ocultar contraseña',
    },
  ],
  'login/password-label': [
    {
      'type': 0,
      'value': 'Contraseña',
    },
  ],
  'login/password-show': [
    {
      'type': 0,
      'value': 'Mostrar contraseña',
    },
  ],
  'login/password-step/forgot-password': [
    {
      'type': 0,
      'value': '¿Olvidaste tu contraseña?',
    },
  ],
  'login/password-step/heading': [
    {
      'type': 0,
      'value': 'Ingresa tu contraseña',
    },
  ],
  'login/password-step/invalid-password': [
    {
      'type': 0,
      'value': 'Contraseña incorrecta.',
    },
  ],
  'login/password-step/rate-limited': [
    {
      'type': 0,
      'value': 'Demasiados intentos. Espera un minuto antes de volver a intentarlo.',
    },
  ],
  'login/password-step/rate-limited/body': [
    {
      'type': 0,
      'value': 'Puedes volver a intentarlo en:',
    },
  ],
  'login/password-step/rate-limited/heading': [
    {
      'type': 0,
      'value': 'Por tu seguridad, pausamos los intentos de inicio de sesión por un momento.',
    },
  ],
  'login/password-step/signing-in-as': [
    {
      'type': 0,
      'value': 'Ingresando como',
    },
  ],
  'login/password-step/use-another-email': [
    {
      'type': 0,
      'value': 'Usar otro correo',
    },
  ],
  'login/privacy-link': [
    {
      'type': 0,
      'value': 'Aviso de privacidad',
    },
  ],
  'login/rate-limited': [
    {
      'type': 0,
      'value': 'Demasiados intentos. Espera un minuto antes de volver a intentarlo.',
    },
  ],
  'login/rate-limited/body': [
    {
      'type': 0,
      'value': 'Puedes volver a intentarlo en:',
    },
  ],
  'login/rate-limited/heading': [
    {
      'type': 0,
      'value': 'Por tu seguridad, pausamos los intentos de inicio de sesión por un momento.',
    },
  ],
  'login/reactivate/body': [
    {
      'type': 0,
      'value':
        'Si continúas, tu cuenta se reactivará automáticamente y podrás volver a usarla con normalidad.',
    },
  ],
  'login/reactivate/cancel': [
    {
      'type': 0,
      'value': 'Cancelar',
    },
  ],
  'login/reactivate/confirm': [
    {
      'type': 0,
      'value': 'Sí, reactivar mi cuenta',
    },
  ],
  'login/reactivate/expired': [
    {
      'type': 0,
      'value':
        'Este enlace de reactivación ya no es válido o expiró. Vuelve a iniciar sesión para pedir uno nuevo.',
    },
  ],
  'login/reactivate/heading': [
    {
      'type': 0,
      'value': 'Tu cuenta está desactivada',
    },
  ],
  'login/session-expired': [
    {
      'type': 0,
      'value': 'Tu sesión expiró. Vuelve a entrar para continuar.',
    },
  ],
  'login/submit': [
    {
      'type': 0,
      'value': 'Iniciar sesión',
    },
  ],
  'login/subtext': [
    {
      'type': 0,
      'value': 'Escribe tu correo o continúa con un proveedor de abajo.',
    },
  ],
  'login/subtext-no-oauth': [
    {
      'type': 0,
      'value': 'Escribe tu correo para continuar.',
    },
  ],
  'login/terms-link': [
    {
      'type': 0,
      'value': 'Términos y condiciones',
    },
  ],
  'login/totp/code-label': [
    {
      'type': 0,
      'value': 'Código de autenticación',
    },
  ],
  'login/totp/heading': [
    {
      'type': 0,
      'value': 'Ingresa el código de tu app de autenticación',
    },
  ],
  'login/totp/invalid-code': [
    {
      'type': 0,
      'value': 'Código de autenticación inválido.',
    },
  ],
  'login/totp/rate-limited': [
    {
      'type': 0,
      'value': 'Demasiados intentos. Espera un minuto antes de volver a intentarlo.',
    },
  ],
  'login/totp/rate-limited/body': [
    {
      'type': 0,
      'value': 'Puedes volver a intentarlo en:',
    },
  ],
  'login/totp/rate-limited/heading': [
    {
      'type': 0,
      'value': 'Por tu seguridad, pausamos los intentos de inicio de sesión por un momento.',
    },
  ],
  'login/totp/signing-in-as': [
    {
      'type': 0,
      'value': 'Ingresando como ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'login/totp/unexpected-error': [
    {
      'type': 0,
      'value': 'Algo no salió bien al verificar tu código. Intenta de nuevo en un momento.',
    },
  ],
  'login/unexpected-error': [
    {
      'type': 0,
      'value': 'Algo salió mal al iniciar tu sesión. Inténtalo de nuevo.',
    },
  ],
  'logout/cancel-link': [
    {
      'type': 0,
      'value': 'Mejor no',
    },
  ],
  'logout/confirm-description': [
    {
      'type': 0,
      'value': 'Tendrás que volver a ingresar en este dispositivo.',
    },
  ],
  'logout/heading': [
    {
      'type': 0,
      'value': 'Cerrar sesión',
    },
  ],
  'logout/submit': [
    {
      'type': 0,
      'value': 'Cerrar sesión',
    },
  ],
  'password/recovery/callback-heading': [
    {
      'type': 0,
      'value': 'Restablece tu contraseña',
    },
  ],
  'password/recovery/callback-subtext': [
    {
      'type': 0,
      'value': 'Enviamos un código de recuperación a ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'password/recovery/code-label': [
    {
      'type': 0,
      'value': 'Código de recuperación',
    },
  ],
  'password/recovery/confirm-label': [
    {
      'type': 0,
      'value': 'Confirmar contraseña',
    },
  ],
  'password/recovery/have-code-link': [
    {
      'type': 0,
      'value': 'Ya tengo mi código',
    },
  ],
  'password/recovery/mismatch': [
    {
      'type': 0,
      'value': 'Las contraseñas no coinciden.',
    },
  ],
  'password/recovery/password-hide': [
    {
      'type': 0,
      'value': 'Ocultar contraseña',
    },
  ],
  'password/recovery/password-label': [
    {
      'type': 0,
      'value': 'Nueva contraseña',
    },
  ],
  'password/recovery/password-show': [
    {
      'type': 0,
      'value': 'Mostrar contraseña',
    },
  ],
  'password/recovery/request-body': [
    {
      'type': 0,
      'value': 'Si existe una cuenta para ',
    },
    {
      'type': 1,
      'value': 'email',
    },
    {
      'type': 0,
      'value': ', se envió un código de recuperación.',
    },
  ],
  'password/recovery/request-heading': [
    {
      'type': 0,
      'value': 'Revisa tu correo',
    },
  ],
  'password/recovery/submit': [
    {
      'type': 0,
      'value': 'Restablecer contraseña',
    },
  ],
  'password/recovery/weak-password': [
    {
      'type': 0,
      'value': 'Esta contraseña no cumple los requisitos de contraseña.',
    },
  ],
  'phone/confirm/code-label': [
    {
      'type': 0,
      'value': 'Código de verificación',
    },
  ],
  'phone/confirm/heading': [
    {
      'type': 0,
      'value': 'Ingresa el código que te enviamos',
    },
  ],
  'phone/confirm/sent-to': [
    {
      'type': 0,
      'value': 'Enviamos un código a ',
    },
    {
      'type': 1,
      'value': 'phone',
    },
    {
      'type': 0,
      'value': '.',
    },
  ],
  'phone/enroll/body': [
    {
      'type': 0,
      'value': 'Te enviaremos un código de un solo uso para confirmar que este número es tuyo.',
    },
  ],
  'phone/enroll/heading': [
    {
      'type': 0,
      'value': 'Verifica tu número de teléfono',
    },
  ],
  'phone/enroll/phone-label': [
    {
      'type': 0,
      'value': 'Número de teléfono',
    },
  ],
  'phone/enroll/phone-placeholder': [
    {
      'type': 0,
      'value': '+52 55 1234 5678',
    },
  ],
  'phone/enroll/submit': [
    {
      'type': 0,
      'value': 'Enviar código',
    },
  ],
  'totp/confirm/heading': [
    {
      'type': 0,
      'value': 'Confirmar app de autenticación',
    },
  ],
  'totp/enroll/code-label': [
    {
      'type': 0,
      'value': 'Código de autenticación',
    },
  ],
  'totp/enroll/heading': [
    {
      'type': 0,
      'value': 'Configurar una app de autenticación',
    },
  ],
  'totp/enroll/invalid-code': [
    {
      'type': 0,
      'value': 'Código de autenticación inválido — escanea el nuevo código a continuación.',
    },
  ],
  'totp/enroll/scan-aria-label': [
    {
      'type': 0,
      'value': 'Escanea este código QR con tu app de autenticación',
    },
  ],
  'totp/enroll/scan-instructions': [
    {
      'type': 0,
      'value': 'Escanéalo con tu app de autenticación, o ingresa la clave manualmente:',
    },
  ],
  'totp/enroll/submit': [
    {
      'type': 0,
      'value': 'Confirmar',
    },
  ],
}
