/**
 * Compiles the plain message catalogs (`ui/sdk/messages/{en,es}.ts`) to ICU AST and writes one
 * module per language under `ui/sdk/messages/compiled/`. `iamMessages` serves those modules to a
 * `@zanix/space` app, so the AST is ready when `loadMessages` returns it and the app's formatter
 * does not parse anything at run time. Run it with `deno task gen:messages` after editing a
 * catalog; a test fails when the generated files are out of date.
 *
 * The parser is a development dependency: the published modules are plain data.
 */
import { parse } from '@formatjs/icu-messageformat-parser'
import { IAM_UI_MESSAGES_EN } from '../ui/sdk/messages/en.ts'
import { IAM_UI_MESSAGES_ES } from '../ui/sdk/messages/es.ts'

const CATALOGS: Record<string, Readonly<Record<string, string>>> = {
  en: IAM_UI_MESSAGES_EN,
  es: IAM_UI_MESSAGES_ES,
}

const OUT_DIR = new URL('../ui/sdk/messages/compiled/', import.meta.url)

await Promise.all(
  Object.entries(CATALOGS).map(async ([lang, catalog]) => {
    const compiled = Object.fromEntries(
      Object.entries(catalog).map(([key, value]) => [key, parse(value)]),
    )
    const name = `IAM_UI_MESSAGES_${lang.toUpperCase()}_COMPILED`
    const source = `// Generated by \`deno task gen:messages\` from \`../${lang}.ts\`. Do not edit.
/** The ${lang} catalog as ICU AST. */
export const ${name}: Readonly<
  Record<string, { type: number; value?: string; [key: string]: unknown }[]>
> = ${JSON.stringify(compiled, null, 2)}
`
    await Deno.writeTextFile(new URL(`${lang}.ts`, OUT_DIR), source)
  }),
)
